### ISSUE TITLE
steps.setup_sp.outputs.plugin-version returns nothing when using #define PLUGIN_VERSION

### ISSUE THREAD

**Issue by flleeppyy** [rumblefrog/setup-sp#13]
I use `#define PLUGIN_VERSION "1.2.3"` to set my plugin version, then use it in the `Plugin` like so

```cpp

#define PLUGIN_VERSION "1.2.3"

public Plugin myinfo = {
  name = "My plugin",
  author = "Flleeppyy",
  description = "blah blah",
  version  = PLUGIN_VERSION,
};


// some where down the line
public void OnPluginStart() {
  CreateConVar("sm_mypluginlol_version", PLUGIN_VERSION, "Current Plugin Version", FLAGS_CVARS|FCVAR_DONTRECORD|FCVAR_SPONLY);
 // ...
}
```

When I use PLUGIN_VERSION macro as the plugin version, setup-sp doesn't detect the plugin version when I use `steps.setup_sp.outputs.plugin-version` in my workflow.

**Comment by rumblefrog** [comment]
Where's the workflow code?

**Comment by flleeppyy** [comment]
```
name: Compile and release

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: echo SCRIPTS_PATH=$(pwd) >> $GITHUB_ENV
      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.11.x"
          version-file: ./scripting/rtd.sp

      - name: Compile plugins
        run: |
          mkdir plugins
          cd scripting
          spcomp -w234 -O2 -v2 -i"include" -o"../plugins/rtd.smx" rtd.sp
          echo "===OUT FILES==="
          cd ../plugins
          ls
          echo "===VERSION==="
          echo ${{ steps.setup_sp.outputs.plugin-version }}
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Changelog
        id: changelog
        uses: mindsers/changelog-reader-action@v2.0.0

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: |
          zip -qq -r rtd-pg-${{ steps.setup_sp.outputs.plugin-version }}.zip gamedata plugins configs scripting
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.setup_sp.outputs.plugin-version }}
          artifacts: "./rtd-pg-${{ steps.setup_sp.outputs.plugin-version }}.zip"
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          allowUpdates: true
          prerelease: true
          replacesArtifacts: true
```
