### ISSUE TITLE
setup-sp compiles successfully, but does not read version correctly.

### ISSUE THREAD

**Issue by flleeppyy** [rumblefrog/setup-sp#14]
In my plugin, I have my version set using define.
```
#define PLUGIN_VERSION  "2.3.6-beta.2"
```
I push my commits and the workflow succeeds but the version is not correct, and outputs 2.3.6

[Here is the actions workflow log](https://haste.fleepy.tv/debabacufosa)

Workflow config
```
name: Compile and release

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: echo SCRIPTS_PATH=$(pwd) >> $GITHUB_ENV
      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.11.x"
          version-file: ./scripting/rtd.sp
          define-name: "PLUGIN_VERSION"

      - name: Compile plugins
        run: |
          mkdir plugins
          cd scripting
          spcomp -w234 -O2 -v2 -i"include" -o"../plugins/rtd.smx" rtd.sp
          echo "===OUT FILES==="
          cd ../plugins
          ls
          echo "===VERSION==="
          echo ${{ steps.setup_sp.outputs.plugin-version }}
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Changelog
        id: changelog
        uses: mindsers/changelog-reader-action@v2.0.0

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: |
          zip -qq -r rtd-pg-${{ steps.setup_sp.outputs.plugin-version }}.zip gamedata plugins configs scripting
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.setup_sp.outputs.plugin-version }}
          artifacts: "./rtd-pg-${{ steps.setup_sp.outputs.plugin-version }}.zip"
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          allowUpdates: true
          prerelease: true
          replacesArtifacts: true

```
